name: Evaluation 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  evaluate:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Print information
      run: ls
    
    - name: Download Amandroid
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: Amandroid_3.1.2
        file: Amandroid_3.1.2_Release.zip
  
    - name: Print information
      run: ls, ls Amandroid_3.1.2 
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
