name: Evaluation 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "evaluate"
  evaluate:
######################################################################
#                 Setup environments 
######################################################################
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
   
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.232' # The JDK version to make available on the path.
        java-package: jdk+fx # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - run: java -version  
######################################################################
#                 Download TaintBench Framework Tools 
######################################################################
#########################################
#        BREW 
#########################################
    - name: Download BREW
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TBFramework'
        path: download
        file: BREW-2.0.0-SNAPSHOT-EMSE.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/BREW-2.0.0-SNAPSHOT-EMSE.zip -d TBFramework

    - run: ls TBFramework/BREW-2.0.0-SNAPSHOT-EMSE

#########################################
#      TBMapper
#########################################
    - name: Download TBMapper
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TBFramework'
        path: download
        file: TBSaSMapper-1.0-SNAPSHOT-EMSE.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/TBSaSMapper-1.0-SNAPSHOT-EMSE.zip -d TBFramework

    - run: ls TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE

######################################################################
#                 Download Android Platforms  
######################################################################
    - name: Download Android Platforms
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'AndroidPlatforms'
        path: download
        file: platforms.zip 
    
    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/platforms.zip -d .

    - run: ls platforms

######################################################################
#                 Download TaintBench Suite
######################################################################
    - name: Download TaintBench Suite
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintBenchSuite'
        path: download
        file: TaintBench.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/TaintBench.zip -d TaintBench

    - run: ls TaintBench

    - name: Download TaintBench Baseline Findings
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintBenchSuite'
        path: download
        file: findings.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/findings.zip -d .

######################################################################
#                 Download Analysis Tools 
######################################################################
#                   Amandroid 3.1.2
#########################################
    - name: Download Amandroid 3.1.2
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: Amandroid_3.1.2_Release.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq AnalysisTools/Amandroid_3.1.2_Release.zip -d AnalysisTools
#########################################
#                   Amandroid 3.2.0
#########################################

    - name: Download Amandroid 3.2.0
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: Amandroid_3.2.0_Release.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq AnalysisTools/Amandroid_3.2.0_Release.zip -d AnalysisTools
#########################################
#                   FlowDroid April 2017
#########################################
    - name: Download FlowDroid April 2017
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: FlowDroid_April_2017_Nightly.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq AnalysisTools/FlowDroid_April_2017_Nightly.zip -d AnalysisTools/FlowDroid_April_2017_Nightly

###########################################
#                   FlowDroid April 2.7.1          
############################################
    - name: Download FlowDroid 2.7.1
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: FlowDroid_2.7.1_Release.zip 
    
    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq AnalysisTools/FlowDroid_2.7.1_Release.zip -d AnalysisTools
        
######################################################################
    - name: Remove .Zip files
      run: |
          sudo rm AnalysisTools/Amandroid_3.1.2_Release.zip
          sudo rm AnalysisTools/Amandroid_3.2.0_Release.zip 
          sudo rm AnalysisTools/FlowDroid_April_2017_Nightly.zip 
          sudo rm AnalysisTools/FlowDroid_2.7.1_Release.zip
          sudo rm -rf download
    
    - run: ls platforms

    - run: ls TaintBench

    - run: ls findings
    
    - run: ls TBFramework/BREW-2.0.0-SNAPSHOT-EMSE

    - run: ls TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE

    - run: ls AnalysisTools/Amandroid_3.1.2_Release

    - run: ls AnalysisTools/Amandroid_3.2.0_Release
    
    - run: ls AnalysisTools/FlowDroid_April_2017_Nightly

    - run: ls AnalysisTools/FlowDroid_2.7.1_Release

    - run: ls -R .

######################################################################
#                 Run FlowDroid April 2017
######################################################################
    - name: Prepare
      run: |
          sudo chmod +x TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/flushMemory.sh
          sudo chmod +x TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/killpid.sh
          ls -l TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/flushMemory.sh
          ls -l TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/killpid.sh

          sudo cp taintbench_brew_configs/fdold/aqlRunSS.sh AnalysisTools/FlowDroid_April_2017_Nightly/aqlRunSS.sh
          sudo chmod +x AnalysisTools/FlowDroid_April_2017_Nightly/aqlRunSS.sh
          ls -l AnalysisTools/FlowDroid_April_2017_Nightly/aqlRunSS.sh

          sudo cp taintbench_brew_configs/fdold/clear.sh AnalysisTools/FlowDroid_April_2017_Nightly/clear.sh
          sudo chmod +x AnalysisTools/FlowDroid_April_2017_Nightly/clear.sh
          ls -l AnalysisTools/FlowDroid_April_2017_Nightly/clear.sh

          echo remove TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/config.properties
          sudo rm TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/config.properties

          echo copy taintbench_brew_configs/config.properties to TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/config.properties
          sudo mv taintbench_brew_configs/config.properties TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/config.properties

          sudo mv taintbench_brew_configs TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/taintbench_brew_configs

    - name: Run FlowDroid April 2017
      run: |
          sudo chmod -R 777 AnalysisTools/FlowDroid_April_2017_Nightly
          mkdir AnalysisTools/FlowDroid_April_2017_Nightly/results
          sudo chmod -R 777 AnalysisTools/FlowDroid_April_2017_Nightly
          
          sudo chmod -R 777 TBFramework/BREW-2.0.0-SNAPSHOT-EMSE 
          
          sudo chmod -R 777 TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE
          mkdir TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE/results
          sudo chmod -R 777 TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE
          
          cd TBFramework/BREW-2.0.0-SNAPSHOT-EMSE
          ls .
          echo Run FlowDroid April 2017
          java -version 
          java -jar BREW-2.0.0-SNAPSHOT.jar -data data/data_taintbench_16_06_20.zip -d detailed -c taintbench_brew_configs/fdold/config.xml -rules taintbench_brew_configs/fdold/TaintBench/rules_3.xml -r -nogui -t 20m 

  
    - name: Zip Results of FlowDroid April 2017
      uses: TonyBogdanov/zip@1.0
      with:
        args: zip -qq -r /home/runner/work/TaintBench/TaintBench/fdold_results.zip /home/runner/work/TaintBench/TaintBench/AnalysisTools/FlowDroid_April_2017_Nightly/results

    - uses: actions/upload-artifact@v2
      with:
       name: Upload Results of FlowDroid April 2017
       path: /home/runner/work/TaintBench/TaintBench/fdold_results.zip
