name: Evaluation 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  evaluate:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - run: java -version  
      
    - name: Print information
      run: ls
    
    - name: Download Amandroid 3.1.2
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: Amandroid_3.1.2_Release.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./AnalysisTools/Amandroid_3.1.2_Release.zip -d ./AnalysisTools/Amandroid_3.1.2_Release

    - name: Download Amandroid 3.2.2
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: Amandroid_3.2.0_Release.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./AnalysisTools/Amandroid_3.2.0_Release.zip -d ./AnalysisTools/Amandroid_3.2.0_Release

    - name: Download FlowDroid April 2017
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: FlowDroid_April_2017_Nightly.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./AnalysisTools/FlowDroid_April_2017_Nightly.zip -d ./AnalysisTools/FlowDroid_April_2017_Nightly

    - name: Download FlowDroid 2.7.1
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintAnalysisTools'
        path: AnalysisTools
        file: FlowDroid_2.7.1_Release.zip 
    
    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./AnalysisTools/FlowDroid_2.7.1_Release.zip -d ./AnalysisTools/FlowDroid_2.7.1_Release

    - name: Remove .Zip files and Print Downloaded Analysis Tools
      run: |
          rm AnalysisTools/Amandroid_3.1.2_Release.zip
          rm AnalysisTools/Amandroid_3.2.0_Release.zip 
          rm AnalysisTools/FlowDroid_April_2017_Nightly.zip 
          rm AnalysisTools/FlowDroid_2.7.1_Release.zip
          ls AnalysisTools

    - name: Print Each Analysis Tool 
      run: |
          echo Amandroid_3.1.2_Release
          ls AnalysisTools/Amandroid_3.1.2_Release
          echo Amandroid_3.2.0_Release
          ls AnalysisTools/Amandroid_3.2.0_Release
          echo FlowDroid_April_2017_Nightly
          ls AnalysisTools/FlowDroid_April_2017_Nightly
          echo FlowDroid_2.7.1_Release
          ls AnalysisTools/FlowDroid_2.7.1_Release
    
    - name: Download TaintBench Suite
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintBenchSuite'
        path: TaintBench
        file: TaintBench.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./TaintBench/TaintBench.zip -d ./TaintBench/TaintBench

    - name: Remove TaintBench.zip and Print APKs in Downloaded TaintBench
      run: |
         rm TaintBench/TaintBench.zip 
         ls TaintBench/TaintBench
